### ISSUE TITLE
Hide Taskbar with Hotkey

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [ekx/UltrawideHelper#1]
Hi there,

I'm gladly using your tool. Hiding the Taskbar is a great addition, because the borderless windows do not overlap the windows taskbar.
I'd rather want the taskbar to be only hidden when a borderless window game is running than have it hidden all the time.
Is there a way to make it hide by hotkey?

Would be cool to have it added to the shortcutprofiles, so the hotkey makes the game borderless and hides the taskbar. You could add it to the windowprofiles as well, so it automatically gets hidden when a specific game is running and unhides it when it's closed.

**Comment by ekx** [comment]
Hey thanks.
I was already implementing a similar feature, that i've pushed just now... Take a look if that is sufficient for you.

**Comment by Unkn0wn-MDCLXIV** [comment]
Perfect, that's exactly what I was hoping for. Thanks
